// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStocks.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyStocks.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240301012823_fix_portfolio_relationship_5")]
    partial class fix_portfolio_relationship_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyStocks.Domain.Currencies.CurrencyTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("CurrencyTypes");
                });

            modelBuilder.Entity("MyStocks.Domain.PortfolioAggregate.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SharesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("MyStocks.Domain.SharesAggregate.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("ShareType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalShares")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("MyStocks.Domain.SharesAggregate.ShareDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("OperationType");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShareId");

                    b.ToTable("ShareDetails");
                });

            modelBuilder.Entity("MyStocks.Domain.PortfolioAggregate.Portfolio", b =>
                {
                    b.OwnsMany("MyStocks.Domain.PortfolioAggregate.ValueObjects.AssociatedShares", "ShareIds", b1 =>
                        {
                            b1.Property<Guid>("SharedId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SharedId", "PortfolioId");

                            b1.HasIndex("PortfolioId");

                            b1.ToTable("AssociatedShares");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.Navigation("ShareIds");
                });

            modelBuilder.Entity("MyStocks.Domain.SharesAggregate.Share", b =>
                {
                    b.OwnsOne("MyStocks.Domain.Currencies.Currency", "AveragePrice", b1 =>
                        {
                            b1.Property<Guid>("ShareId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CurrencyTypeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("ShareId");

                            b1.HasIndex("CurrencyTypeId");

                            b1.ToTable("Shares");

                            b1.HasOne("MyStocks.Domain.Currencies.CurrencyTypes", "CurrencyType")
                                .WithMany()
                                .HasForeignKey("CurrencyTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ShareId");

                            b1.Navigation("CurrencyType");
                        });

                    b.OwnsOne("MyStocks.Domain.Currencies.Currency", "TotalValueInvested", b1 =>
                        {
                            b1.Property<Guid>("ShareId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CurrencyTypeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("ShareId");

                            b1.HasIndex("CurrencyTypeId");

                            b1.ToTable("Shares");

                            b1.HasOne("MyStocks.Domain.Currencies.CurrencyTypes", "CurrencyType")
                                .WithMany()
                                .HasForeignKey("CurrencyTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ShareId");

                            b1.Navigation("CurrencyType");
                        });

                    b.Navigation("AveragePrice")
                        .IsRequired();

                    b.Navigation("TotalValueInvested")
                        .IsRequired();
                });

            modelBuilder.Entity("MyStocks.Domain.SharesAggregate.ShareDetail", b =>
                {
                    b.HasOne("MyStocks.Domain.SharesAggregate.Share", null)
                        .WithMany("ShareDetails")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MyStocks.Domain.Currencies.Currency", "Price", b1 =>
                        {
                            b1.Property<Guid>("ShareDetailId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CurrencyTypeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("ShareDetailId");

                            b1.HasIndex("CurrencyTypeId");

                            b1.ToTable("ShareDetails");

                            b1.HasOne("MyStocks.Domain.Currencies.CurrencyTypes", "CurrencyType")
                                .WithMany()
                                .HasForeignKey("CurrencyTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ShareDetailId");

                            b1.Navigation("CurrencyType");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("MyStocks.Domain.SharesAggregate.Share", b =>
                {
                    b.Navigation("ShareDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
